name: Delete the previous day's Meishi
on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  Delete_the_previous_day_Meishi:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install
        run: npm install

      - name: Run
        run: npx ts-node --esm ./batch/index.ts